- Book/classes_objects/magic_interfaces_comparable.rst
just adding the php open tag for highlighting like other php code blocks 😄  
( it seems that only this php code block is not highlighted.)
> highlight PHP code

- Book/php7/build_system/building_extensions.rst
- Book/php7/extensions_design/php_functions.rst
- Book/php7/internal_types/strings/zend_strings.rst
- Book/php7/internal_types/zend_resources.rst
- Book/php7/memory_management/memory_debugging.rst
- Book/php7/memory_management/zend_memory_manager.rst
I know it is how these signs should be written in French, but it's not allowed in English.
> Drop spaces before interpunction signs

- Book/php7/extensions_design/php_functions.rst
It was inconsistently described as celsius_to_fahrenheit some of the time.
Tabs have been converted to spaces in some of the related parts of this file, but not all of them (spaces suggested in README.md)
Also, fix a few noticed typos and remove whitespace from the end of lines
> Consistently use fahrenheit to celsius

- Book/php7/build_system/building_php.rst
hot fix for the next warning -at building the book as html stage-:
> WARNING: duplicate label building_php. other instance .....
> fix the duplicate label building_php warning

- Book/php7/extensions_design/extension_skeleton.rst
since KalleZ [commit](https://github.com/php/php-src/commit/f35f45906eac34498c7720326fb9da9fde960871) and the ext_skel had changed entirely, so we need to mention this
I think that this needs some review.
> mention the new ext_skel

- Book/php7/build_system/building_php.rst
Hello, this patch updates the minimal Autoconf requirements for building PHP and its extensions:
- PHP 7.0 and 7.1 require at least Autoconf 2.59
- PHP 7.2 requires Autoconf 2.64+
- PHP 7.3 requires Autoconf 2.68+
using different versionf for each PHP 7.x branch.
> Bump Autoconf minimal required versions

- Book/php7/build_system/building_php.rst
Hello, to not cause too much confusions when building PHP:
The Automake and aclocal were part of the previous PHP build system where Automake created Makefile from the Makefile.in templates and aclocal was used to produce the aclocal.m4. Need for Automake as a dependency to build PHP has been removed in PHP 4.3.0 release and aclocal also in that period of 4.3 releases.
Thanks.
> Remove automake as a dependency to build PHP

- Book/php7/build_system/building_php.rst
The re2c dependency is not optional anymore since PHP > 7.3. This patch extends the dependency explanation.
> Explain the re2c dependency in more details

- Book/hashtables/hashtable_api.rst
Considering the following example
```c
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
typedef int (*foo_pt)(void);
typedef bool (*bar_pt)(void);
static int test(void);
int
main(void)
{
int result;
bar_pt func;
func = (bar_pt)test;
result = func();
if (result)
printf("true\n");
else
printf("false\n");
exit(0);
}
static int
test(void)
{
return 0x800;
}
```
If we run the program above, we will get **false**. The reason is that the return type
of the declaration (`func` is of `bar_pt` type which returns `bool`) and the definition's
(`test` is of `foo_pt` type which returns `int`) are of different size. As a result, the
returned value would be truncated, thus results undefined behavior.
> If you run this program in a `big-endian machine`, the result may be different
In **PHP 5**, …
> Fix potential bug

- Book/php7/build_system/building_php.rst
PHP 7.4 needs 3.0.0 and later bison to generate PHP parser files.
> Bump bison version

- Book/php7/extensions_design.rst
- Book/php7/extensions_design/hooks.rst
Extensions can hook into PHP core in various ways and this chapter is about listing as many of these ways as possible and showing how it works, giving examples, explaining restrictions and downsides.
> Start with Hooks provided by PHP chapter.

- Book/php5/classes_objects/iterators.rst
> Fix the wrong variable name in iterator sample code that caused memory leak.

- Book/_templates/layout.html
- Book/conf.py
Fix the deprecation warning in build script.
Python 2.7
Sphinx v1.8.5
And the original warning message is as following:
`
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/builders/html.py:138: RemovedInSphinx20Warning: builder.css_files is deprecated. Please use app.add_stylesheet() instead.
ret += other
`
> Change the way to add static stylesheets.

- Book/php7/internal_types/strings/zend_strings.rst
Fix the variable name and also replace the tabs with 4-spaces.
> Fix the variable name in sample code.

- Book/php5/hashtables/basic_structure.rst
- README.md
The rendered html `<img height="INT">` is implicitly pixels.
sphinx-build 2.4.4 threw when casting to int().
```
File "/usr/local/lib/python3.7/site-packages/sphinx/writers/html5.py",
line 550, in visit_image
atts['height'] = int(atts['height']) * scale
ValueError: invalid literal for int() with base 10: '265px'
```
The rendered php5 file had `<img height="500">` for 250px and 200%
scale. (The last svg was 81 pixels tall,
and I'm not familiar with why both height and scale are set)
> Fix sphinx build and update link to sphinx docs

- Book/php7/zend_engine/zend_compiler.rst
- Book/php7/zend_engine/zend_executor.rst
Fixes #77
The PHP7 blog posts for 7.2 are fairly up to date, and a much better starting point for new developers than leaving this empty
> Link to php7 blog posts on compiler/executor

- Book/php7/extensions_design/hooks.rst
Since `EG(function_table)` isn't available on MINIT. I also added note about TSRMLS cache when accessing `CG()` from MINIT since the extension skeleton has `ZEND_TSRMLS_CACHE_UPDATE()` in RINIT.
> Reference CG() for internal function hooks on MINIT

- Book/php7/build_system/building_php.rst
This package may be installed in most environments but it's not the case in an ubuntu docker.
> feat: add pkg-config to packages to install

- Book/php7/zvals/casts_and_operations.rst
This PR fixes a typo on "zvals - Casts and Operations", spotted in #100
> Fix a typo on PHP7/ZVALS

- .github/workflows/publish-to-github-pages.yml
This PR fixes the build/publish automation introduced by #109.
Action Steps:
1. Installs Python 3.x;
2. Installs Sphinx;
3. Installs PHP 8.1;
4. Executes the release script.
> Install Sphinx before building release (GHA)

- .github/workflows/publish-to-github-pages.yml
This PR replaces `tsunematsu21/actions-publish-gh-pages` with `JamesIves/github-pages-deploy-action`, which works as expected during my tests.
> Replace publish action

- Book/php7/extensions_design/php_functions.rst
Hi :wave: :slightly_smiling_face: 
The first example to register a C function lacks a `PHP_FE_END` to properly finish the declaration of the `zend_function_entry`. Without this line, I reached a _Segmentation Fault_ ...
Thank you very much for this very important documentation about Php internals! :bow:
> fix: add missing PHP_FE_END in example

- Book/index.rst
- Book/php7/classes_objects.rst
- Book/php7/classes_objects/object_handlers.rst
This file only exists for the PHP 5 part of the book, I wonder if it's time to merge those and just make `master` match the current `master` version of php-src itself.
> Update object handlers

- Book/php7/extensions_design/zend_extensions.rst
Otherwise it is not possible to even load the zend extension on
Windows.
> extension_version_info and zend_extension_entry must be exported

- Book/php7/extensions_design/ini_settings.rst
As the fourth one is being described in this section.
Moreover, the sentence afterwards talks about the last 4 arguments, to a macro which only takes 7.
(PS: doing stuff via the GitHub online interface is a bit of a mess so the commit title is incorrect)
> Use first 3 instead of first 4 in INI registration section

- Book/php7/extensions_design/ini_settings.rst
The texts talks about using the simplest way to register an INI setting but says that we used ``PHP_INI_BEGIN()`` which is always needed as it's to start registering.
The one actually used to register is ``REGISTER_INI_ENTRIES()``
> Update docs to use the correct PHP_INI_ENTRY macro

- Book/php7/classes_objects/object_handlers.rst
See https://github.com/php/php-src/pull/8755
> Update some object handlers to return zend_result

- Book/php7/internal_types/strings/smart_str.rst
This mentions `smart_str_extract()` in the `smart_str` page.
smart_str uses an over-allocated string to optimize for append operations. Functions that use smart_str tend to return the over-allocated string directly. This results in unnecessary memory usage, especially for small strings.
The overhead can be up to 231 bytes for strings smaller than that, and 4095 for other strings. This can be avoided for strings smaller than `4096 - zend_string header size - 1` by reallocating the string.
https://github.com/php/php-src/pull/8902 introduces `smart_str_trim_to_size()`, and calls it in `smart_str_extract()`.
There are other benefits in using `smart_str_extract()` over accessing `.s` directly:
- It will return an empty string if `.s` is null
- It takes car of the trailing _NUL_ byte
- It …
> smart_str: mention smart_str_extract()

- Book/php7/zvals/basic_structure.rst
> a `zend_string` structure, which combines the string length and the string constants in a single allocation
Change "string constants" to "string contents".
> Fix trivial typo in Basic Structure

- Book/php7/internal_types/functions/callables.rst
Describe how to store a callable properly, mention trampolines and what they are
Point to better APIs and pitfalls of some of the existing FCI APIs
> Clarify the handling of callables more

- Book/php7/memory_management/zend_memory_manager.rst
Hey there 👋 
this PR will add a missing documentation about the ZendMM internal design, as well as a section about the lifecycle of the Zend Memory Manager and an example of how to hook into it.
> Add ZendMM internals, lifecycle and how to hook into docs
